# Generated by Django 4.2 on 2023-11-29 03:06

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("startup_name", models.CharField(max_length=200)),
                ("startup_email", models.CharField(max_length=200, unique=True)),
                ("startup_location", models.CharField(max_length=200)),
                ("startup_industry", models.CharField(max_length=200)),
                ("startup_description", models.CharField(max_length=400)),
                ("startup_website_url", models.CharField(max_length=200)),
                ("startup_linkedin_profile", models.CharField(max_length=200)),
                ("startup_phone_number", models.CharField(max_length=200)),
                ("founded_in", models.DateField()),
                (
                    "founders",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "additional_info",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
