# Generated by Django 4.2 on 2023-11-21 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startup_name', models.CharField(max_length=200)),
                ('startup_email', models.CharField(max_length=200, unique=True)),
                ('startup_location', models.CharField(max_length=200)),
                ('startup_industry', models.CharField(max_length=200)),
                ('startup_description', models.CharField(max_length=200)),
                ('founded_in', models.DateField()),
            ],
        ),
    ]
