# Generated by Django 4.2 on 2023-11-27 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("startup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="startup_website_url",
        ),
    ]
