# Generated by Django 4.2 on 2023-11-21 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_description',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('founder_first_name', models.CharField(max_length=200)),
                ('fornder_last_name', models.CharField(max_length=200)),
                ('founder_email', models.CharField(max_length=200)),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Founders_startup', to='startup.startup')),
            ],
        ),
    ]
