# Generated by Django 4.2 on 2023-11-21 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_alter_startup_startup_description_founders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founders',
            old_name='fornder_last_name',
            new_name='founder_last_name',
        ),
        migrations.AlterField(
            model_name='startup',
            name='founded_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
