# Generated by Django 4.2 on 2023-11-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startup", "0002_remove_startup_startup_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="startup_website_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
