# Generated by Django 4.2 on 2023-11-27 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startup", "0003_startup_startup_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="founders",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
