# Generated by Django 4.2 on 2023-11-25 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("startup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("founder_first_name", models.CharField(max_length=200)),
                ("founder_last_name", models.CharField(max_length=200)),
                ("founder_email", models.CharField(max_length=200)),
                (
                    "startup_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Founders_startup",
                        to="startup.startup",
                    ),
                ),
            ],
        ),
    ]
