# Generated by Django 4.2 on 2023-11-17 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
